# frozen_string_literal: true

require 'roar/representer'
require 'roar/json'
require 'roar/json/hal'

require_relative 'presenters/paginated_presenter'
require_relative 'presenters/status_presenter'
require_relative 'presenters/challenge_presenter'
require_relative 'presenters/challenges_presenter'
require_relative 'presenters/user_presenter'
require_relative 'presenters/users_presenter'
require_relative 'presenters/match_presenter'
require_relative 'presenters/matches_presenter'
require_relative 'presenters/user_rank_presenter'
require_relative 'presenters/user_ranks_presenter'
require_relative 'presenters/season_presenter'
require_relative 'presenters/seasons_presenter'
require_relative 'presenters/team_presenter'
require_relative 'presenters/teams_presenter'
require_relative 'presenters/channel_presenter'
require_relative 'presenters/channels_presenter'
require_relative 'presenters/root_presenter'
