# frozen_string_literal: true

require_relative 'models/mixins'
require_relative 'models/details'
require_relative 'models/elo_change'
require_relative 'models/team'
require_relative 'models/channel'
require_relative 'models/elo'
require_relative 'models/user'
require_relative 'models/user_rank'
require_relative 'models/challenge_state'
require_relative 'models/challenge'
require_relative 'models/score'
require_relative 'models/match'
require_relative 'models/season'
require_relative 'models/admin'
